services:

  service:
    build: ./
    restart: always
    ports:
      - "9090:9090"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m
      timeout: 10s
      retries: 3

volumes:
  db-data: