server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: printscript-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URI}
          client-id: ${AUTH_CLIENT_ID}
          client-secret: ${AUTH_CLIENT_SECRET}

services:
  snippetmanager:
    url: ${SNIPPETMANAGER_HOST:http://localhost:8081}
  asset:
    url: ${ASSET_HOST:http://localhost:8081}

